import os
import shutil
from typing import Dict, List, Any

def export_workflow_to_python(workflow_data: Dict[str, Any], output_path: str, templates_dir: str):
    actions = workflow_data.get("actions", [])
    if not actions:
        raise ValueError("Workflow has no actions to export.")

    base_dir = os.path.dirname(output_path)
    if not base_dir:
        base_dir = "."

    os.makedirs(base_dir, exist_ok=True)
    
    assets_dir = os.path.join(base_dir, "assets")
    os.makedirs(assets_dir, exist_ok=True)
    
    lines = []
    lines.append("#!/usr/bin/env python3")
    lines.append("# -*- coding: utf-8 -*-")
    lines.append(f"# Auto-generated by Desktop Automator")
    lines.append(f"# Workflow: {workflow_data.get('name', 'Unknown')}")
    lines.append("")
    lines.append("import time")
    lines.append("import sys")
    lines.append("import os")
    lines.append("import logging")
    lines.append("")
    lines.append("try:")
    lines.append("    import pyautogui")
    lines.append("except ImportError:")
    lines.append("    print('Please install required packages: pip install pyautogui opencv-python Pillow')")
    lines.append("    sys.exit(1)")
    lines.append("")
    lines.append("logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(message)s')")
    lines.append("logger = logging.getLogger(__name__)")
    lines.append("")
    lines.append("def get_asset(filename):")
    lines.append("    return os.path.join(os.path.dirname(os.path.abspath(__file__)), 'assets', filename)")
    lines.append("")
    lines.append("def main():")
    lines.append("    logger.info('Starting automation script...')")
    lines.append("    pyautogui.FAILSAFE = True")
    lines.append("    time.sleep(1)")
    lines.append("")
    
    indent = "    "
    
    def add_action(a: dict, lvl: int = 1):
        ind = indent * lvl
        atype = a.get("type", "")
        if not a.get("enabled", True):
            lines.append(f"{ind}# [DISABLED] {atype}")
            return
            
        label = a.get("label") or a.get("note") or atype
        lines.append(f"{ind}# --- Action: {label} ---")
        
        if atype == "sleep":
            duration = a.get("duration", 1)
            lines.append(f"{ind}logger.info('Sleeping for {duration} seconds')")
            lines.append(f"{ind}time.sleep({duration})")
            
        elif atype == "click":
            x, y = a.get("x", 0), a.get("y", 0)
            btn = a.get("button", "left")
            clicks = a.get("clicks", 1)
            lines.append(f"{ind}logger.info('Clicking at ({x}, {y})')")
            lines.append(f"{ind}pyautogui.click(x={x}, y={y}, button='{btn}', clicks={clicks})")
            
        elif atype == "type_text" or atype == "type":
            txt = a.get("text", a.get("value", a.get("key", ""))).replace("'", "\\'")
            lines.append(f"{ind}logger.info('Typing text')")
            lines.append(f"{ind}pyautogui.typewrite('{txt}')")
            
        elif atype == "hotkey":
            keys = a.get("keys", [])
            args = ", ".join([f"'{k}'" for k in keys])
            lines.append(f"{ind}logger.info('Pressing hotkey: {args}')")
            lines.append(f"{ind}pyautogui.hotkey({args})")
            
        elif atype in ("assert_template", "wait_for_template", "click_template", "click"):
            tmpl = a.get("template") or a.get("template_image")
            if tmpl:
                src = os.path.join(templates_dir, tmpl)
                if os.path.exists(src):
                    shutil.copy(src, os.path.join(assets_dir, tmpl))
                
                conf = a.get("confidence", 0.8)
                lines.append(f"{ind}logger.info('Looking for template: {tmpl}')")
                
                if atype == "wait_for_template":
                    timeout = a.get("timeout", 10)
                    lines.append(f"{ind}start_time = time.time()")
                    lines.append(f"{ind}found = False")
                    lines.append(f"{ind}while time.time() - start_time < {timeout}:")
                    lines.append(f"{ind}{indent}loc = pyautogui.locateOnScreen(get_asset('{tmpl}'), confidence={conf})")
                    lines.append(f"{ind}{indent}if loc:")
                    lines.append(f"{ind}{indent}{indent}found = True")
                    lines.append(f"{ind}{indent}{indent}break")
                    lines.append(f"{ind}{indent}time.sleep(0.5)")
                    lines.append(f"{ind}if not found:")
                    lines.append(f"{ind}{indent}logger.warning('Template not found')")
                    if a.get("on_timeout") == "error":
                        lines.append(f"{ind}{indent}raise TimeoutError('Template {tmpl} not found')")
                else:
                    lines.append(f"{ind}loc = pyautogui.locateOnScreen(get_asset('{tmpl}'), confidence={conf})")
                    lines.append(f"{ind}if not loc:")
                    lines.append(f"{ind}{indent}raise ValueError('Template {tmpl} not found')")
                    if "click" in atype:
                        lines.append(f"{ind}else:")
                        lines.append(f"{ind}{indent}center = pyautogui.center(loc)")
                        lines.append(f"{ind}{indent}pyautogui.click(center.x, center.y)")
                    
        elif atype == "open_url":
            url = a.get("url", "")
            lines.append(f"{ind}import webbrowser")
            lines.append(f"{ind}logger.info('Opening URL: {url}')")
            lines.append(f"{ind}webbrowser.open('{url}')")
            
        elif atype == "run_command":
            cmd = a.get("command", "")
            lines.append(f"{ind}import subprocess")
            lines.append(f"{ind}logger.info('Running command')")
            lines.append(f"{ind}subprocess.run('{cmd}', shell=True)")
            
        elif atype == "group":
            group_actions = a.get("actions", [])
            lines.append(f"{ind}logger.info('Entering Group')")
            for ca in group_actions:
                add_action(ca, lvl)
                
        else:
            lines.append(f"{ind}logger.warning('Action type {atype} is not fully supported by exporter yet.')")
            
        lines.append("")

    for action in actions:
        add_action(action, 1)
        
    lines.append("    logger.info('Automation completed successfully!')")
    lines.append("")
    lines.append("if __name__ == '__main__':")
    lines.append("    try:")
    lines.append("        main()")
    lines.append("    except Exception as e:")
    lines.append("        logger.error(f'Execution failed: {e}')")
    lines.append("        sys.exit(1)")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
